// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HoldingCurrency.
const (
	HoldingCurrencyEUR HoldingCurrency = "EUR"
	HoldingCurrencyINR HoldingCurrency = "INR"
)

// Valid indicates whether the value is a known member of the HoldingCurrency enum.
func (e HoldingCurrency) Valid() bool {
	switch e {
	case HoldingCurrencyEUR:
		return true
	case HoldingCurrencyINR:
		return true
	default:
		return false
	}
}

// Defines values for HoldingExchange.
const (
	HoldingExchangeBSE    HoldingExchange = "BSE"
	HoldingExchangeNASDAQ HoldingExchange = "NASDAQ"
	HoldingExchangeNSE    HoldingExchange = "NSE"
	HoldingExchangeNYSE   HoldingExchange = "NYSE"
	HoldingExchangeOTHER  HoldingExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingExchange enum.
func (e HoldingExchange) Valid() bool {
	switch e {
	case HoldingExchangeBSE:
		return true
	case HoldingExchangeNASDAQ:
		return true
	case HoldingExchangeNSE:
		return true
	case HoldingExchangeNYSE:
		return true
	case HoldingExchangeOTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingType.
const (
	HoldingTypeEtf   HoldingType = "etf"
	HoldingTypeStock HoldingType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingType enum.
func (e HoldingType) Valid() bool {
	switch e {
	case HoldingTypeEtf:
		return true
	case HoldingTypeStock:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputCurrency.
const (
	HoldingInputCurrencyEUR HoldingInputCurrency = "EUR"
	HoldingInputCurrencyINR HoldingInputCurrency = "INR"
)

// Valid indicates whether the value is a known member of the HoldingInputCurrency enum.
func (e HoldingInputCurrency) Valid() bool {
	switch e {
	case HoldingInputCurrencyEUR:
		return true
	case HoldingInputCurrencyINR:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputExchange.
const (
	HoldingInputExchangeBSE    HoldingInputExchange = "BSE"
	HoldingInputExchangeNASDAQ HoldingInputExchange = "NASDAQ"
	HoldingInputExchangeNSE    HoldingInputExchange = "NSE"
	HoldingInputExchangeNYSE   HoldingInputExchange = "NYSE"
	HoldingInputExchangeOTHER  HoldingInputExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingInputExchange enum.
func (e HoldingInputExchange) Valid() bool {
	switch e {
	case HoldingInputExchangeBSE:
		return true
	case HoldingInputExchangeNASDAQ:
		return true
	case HoldingInputExchangeNSE:
		return true
	case HoldingInputExchangeNYSE:
		return true
	case HoldingInputExchangeOTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputType.
const (
	HoldingInputTypeEtf   HoldingInputType = "etf"
	HoldingInputTypeStock HoldingInputType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingInputType enum.
func (e HoldingInputType) Valid() bool {
	switch e {
	case HoldingInputTypeEtf:
		return true
	case HoldingInputTypeStock:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceCurrency.
const (
	EUR HoldingWithPriceCurrency = "EUR"
	INR HoldingWithPriceCurrency = "INR"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceCurrency enum.
func (e HoldingWithPriceCurrency) Valid() bool {
	switch e {
	case EUR:
		return true
	case INR:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceExchange.
const (
	BSE    HoldingWithPriceExchange = "BSE"
	NASDAQ HoldingWithPriceExchange = "NASDAQ"
	NSE    HoldingWithPriceExchange = "NSE"
	NYSE   HoldingWithPriceExchange = "NYSE"
	OTHER  HoldingWithPriceExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceExchange enum.
func (e HoldingWithPriceExchange) Valid() bool {
	switch e {
	case BSE:
		return true
	case NASDAQ:
		return true
	case NSE:
		return true
	case NYSE:
		return true
	case OTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceType.
const (
	Etf   HoldingWithPriceType = "etf"
	Stock HoldingWithPriceType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceType enum.
func (e HoldingWithPriceType) Valid() bool {
	switch e {
	case Etf:
		return true
	case Stock:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// Holding defines model for Holding.
type Holding struct {
	// AvgCostPrice Average purchase price per share in the holding's currency
	AvgCostPrice *float64   `json:"avg_cost_price,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`

	// Currency Currency in which avg_cost_price and realized_pnl are denominated
	Currency *HoldingCurrency `json:"currency,omitempty"`
	Exchange *HoldingExchange `json:"exchange,omitempty"`

	// Id MongoDB ObjectID
	Id    *string `json:"id,omitempty"`
	Notes *string `json:"notes,omitempty"`

	// RealizedPnl Profit/loss from shares already sold, in the holding's currency
	RealizedPnl *float64 `json:"realized_pnl,omitempty"`

	// Script Display name (e.g. "TCS", "GOLD BEES")
	Script *string `json:"script,omitempty"`

	// StocksOwned Current quantity held
	StocksOwned *float64 `json:"stocks_owned,omitempty"`

	// Symbol Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL")
	Symbol    *string      `json:"symbol,omitempty"`
	Type      *HoldingType `json:"type,omitempty"`
	UpdatedAt *time.Time   `json:"updated_at,omitempty"`
}

// HoldingCurrency Currency in which avg_cost_price and realized_pnl are denominated
type HoldingCurrency string

// HoldingExchange defines model for Holding.Exchange.
type HoldingExchange string

// HoldingType defines model for Holding.Type.
type HoldingType string

// HoldingInput defines model for HoldingInput.
type HoldingInput struct {
	AvgCostPrice *float64 `json:"avg_cost_price,omitempty"`

	// Currency Currency in which avg_cost_price and realized_pnl are denominated
	Currency    *HoldingInputCurrency `json:"currency,omitempty"`
	Exchange    HoldingInputExchange  `json:"exchange"`
	Notes       *string               `json:"notes,omitempty"`
	RealizedPnl *float64              `json:"realized_pnl,omitempty"`
	Script      string                `json:"script"`
	StocksOwned *float64              `json:"stocks_owned,omitempty"`
	Symbol      *string               `json:"symbol,omitempty"`
	Type        HoldingInputType      `json:"type"`
}

// HoldingInputCurrency Currency in which avg_cost_price and realized_pnl are denominated
type HoldingInputCurrency string

// HoldingInputExchange defines model for HoldingInput.Exchange.
type HoldingInputExchange string

// HoldingInputType defines model for HoldingInput.Type.
type HoldingInputType string

// HoldingWithPrice defines model for HoldingWithPrice.
type HoldingWithPrice struct {
	// AvgCostPrice Average purchase price per share in the holding's currency
	AvgCostPrice *float64 `json:"avg_cost_price,omitempty"`

	// CostPrice stocks_owned × avg_cost_price
	CostPrice    *float64   `json:"cost_price,omitempty"`
	CostPriceEur *float64   `json:"cost_price_eur,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`

	// Currency Currency in which avg_cost_price and realized_pnl are denominated
	Currency     *HoldingWithPriceCurrency `json:"currency,omitempty"`
	CurrentPrice *float64                  `json:"current_price,omitempty"`

	// CurrentValue stocks_owned × current_price
	CurrentValue    *float64                  `json:"current_value,omitempty"`
	CurrentValueEur *float64                  `json:"current_value_eur,omitempty"`
	Exchange        *HoldingWithPriceExchange `json:"exchange,omitempty"`

	// Id MongoDB ObjectID
	Id         *string `json:"id,omitempty"`
	Notes      *string `json:"notes,omitempty"`
	PriceError *string `json:"price_error,omitempty"`

	// RealizedPnl Profit/loss from shares already sold, in the holding's currency
	RealizedPnl    *float64 `json:"realized_pnl,omitempty"`
	RealizedPnlEur *float64 `json:"realized_pnl_eur,omitempty"`

	// Script Display name (e.g. "TCS", "GOLD BEES")
	Script *string `json:"script,omitempty"`

	// StocksOwned Current quantity held
	StocksOwned *float64 `json:"stocks_owned,omitempty"`

	// Symbol Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL")
	Symbol *string               `json:"symbol,omitempty"`
	Type   *HoldingWithPriceType `json:"type,omitempty"`

	// UnrealizedPnl current_value − cost_price
	UnrealizedPnl    *float64   `json:"unrealized_pnl,omitempty"`
	UnrealizedPnlEur *float64   `json:"unrealized_pnl_eur,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
}

// HoldingWithPriceCurrency Currency in which avg_cost_price and realized_pnl are denominated
type HoldingWithPriceCurrency string

// HoldingWithPriceExchange defines model for HoldingWithPrice.Exchange.
type HoldingWithPriceExchange string

// HoldingWithPriceType defines model for HoldingWithPrice.Type.
type HoldingWithPriceType string

// PricesResponse defines model for PricesResponse.
type PricesResponse struct {
	// EurRate Live INR→EUR rate used for conversions
	EurRate  *float64            `json:"eur_rate,omitempty"`
	Holdings *[]HoldingWithPrice `json:"holdings,omitempty"`
}

// Summary defines model for Summary.
type Summary struct {
	EurRate              *float64 `json:"eur_rate,omitempty"`
	TotalCost            *float64 `json:"total_cost,omitempty"`
	TotalCostEur         *float64 `json:"total_cost_eur,omitempty"`
	TotalCurrentValue    *float64 `json:"total_current_value,omitempty"`
	TotalCurrentValueEur *float64 `json:"total_current_value_eur,omitempty"`
	TotalRealized        *float64 `json:"total_realized,omitempty"`
	TotalRealizedEur     *float64 `json:"total_realized_eur,omitempty"`
	TotalUnrealized      *float64 `json:"total_unrealized,omitempty"`
	TotalUnrealizedEur   *float64 `json:"total_unrealized_eur,omitempty"`
}

// BadGateway defines model for BadGateway.
type BadGateway = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// GetForexRateParams defines parameters for GetForexRate.
type GetForexRateParams struct {
	From *string `form:"from,omitempty" json:"from,omitempty"`
	To   *string `form:"to,omitempty" json:"to,omitempty"`
}

// GetMarketPriceParams defines parameters for GetMarketPrice.
type GetMarketPriceParams struct {
	// Symbol Yahoo Finance ticker (e.g. TCS.NS, AAPL, GOLDBEES.NS)
	Symbol string `form:"symbol" json:"symbol"`
}

// CreateHoldingJSONRequestBody defines body for CreateHolding for application/json ContentType.
type CreateHoldingJSONRequestBody = HoldingInput

// UpdateHoldingJSONRequestBody defines body for UpdateHolding for application/json ContentType.
type UpdateHoldingJSONRequestBody = HoldingInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all holdings
	// (GET /holdings)
	ListHoldings(ctx echo.Context) error
	// Add a new holding
	// (POST /holdings)
	CreateHolding(ctx echo.Context) error
	// Delete a holding
	// (DELETE /holdings/{id})
	DeleteHolding(ctx echo.Context, id string) error
	// Get a single holding
	// (GET /holdings/{id})
	GetHolding(ctx echo.Context, id string) error
	// Update a holding
	// (PUT /holdings/{id})
	UpdateHolding(ctx echo.Context, id string) error
	// Get forex exchange rate
	// (GET /market/forex)
	GetForexRate(ctx echo.Context, params GetForexRateParams) error
	// Get live price for any symbol
	// (GET /market/price)
	GetMarketPrice(ctx echo.Context, params GetMarketPriceParams) error
	// Get all holdings enriched with live market prices
	// (GET /prices)
	GetPrices(ctx echo.Context) error
	// Portfolio-level summary with live P&L
	// (GET /summary)
	GetSummary(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListHoldings converts echo context to params.
func (w *ServerInterfaceWrapper) ListHoldings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListHoldings(ctx)
	return err
}

// CreateHolding converts echo context to params.
func (w *ServerInterfaceWrapper) CreateHolding(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateHolding(ctx)
	return err
}

// DeleteHolding converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteHolding(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteHolding(ctx, id)
	return err
}

// GetHolding converts echo context to params.
func (w *ServerInterfaceWrapper) GetHolding(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHolding(ctx, id)
	return err
}

// UpdateHolding converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateHolding(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateHolding(ctx, id)
	return err
}

// GetForexRate converts echo context to params.
func (w *ServerInterfaceWrapper) GetForexRate(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForexRateParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", ctx.QueryParams(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", ctx.QueryParams(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetForexRate(ctx, params)
	return err
}

// GetMarketPrice converts echo context to params.
func (w *ServerInterfaceWrapper) GetMarketPrice(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMarketPriceParams
	// ------------- Required query parameter "symbol" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "symbol", ctx.QueryParams(), &params.Symbol, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter symbol: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMarketPrice(ctx, params)
	return err
}

// GetPrices converts echo context to params.
func (w *ServerInterfaceWrapper) GetPrices(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPrices(ctx)
	return err
}

// GetSummary converts echo context to params.
func (w *ServerInterfaceWrapper) GetSummary(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSummary(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/holdings", wrapper.ListHoldings, options.OperationMiddlewares["listHoldings"]...)
	router.POST(options.BaseURL+"/holdings", wrapper.CreateHolding, options.OperationMiddlewares["createHolding"]...)
	router.DELETE(options.BaseURL+"/holdings/:id", wrapper.DeleteHolding, options.OperationMiddlewares["deleteHolding"]...)
	router.GET(options.BaseURL+"/holdings/:id", wrapper.GetHolding, options.OperationMiddlewares["getHolding"]...)
	router.PUT(options.BaseURL+"/holdings/:id", wrapper.UpdateHolding, options.OperationMiddlewares["updateHolding"]...)
	router.GET(options.BaseURL+"/market/forex", wrapper.GetForexRate, options.OperationMiddlewares["getForexRate"]...)
	router.GET(options.BaseURL+"/market/price", wrapper.GetMarketPrice, options.OperationMiddlewares["getMarketPrice"]...)
	router.GET(options.BaseURL+"/prices", wrapper.GetPrices, options.OperationMiddlewares["getPrices"]...)
	router.GET(options.BaseURL+"/summary", wrapper.GetSummary, options.OperationMiddlewares["getSummary"]...)

}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type ListHoldingsRequestObject struct {
}

type ListHoldingsResponseObject interface {
	VisitListHoldingsResponse(w http.ResponseWriter) error
}

type ListHoldings200JSONResponse []Holding

func (response ListHoldings200JSONResponse) VisitListHoldingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHoldingRequestObject struct {
	Body *CreateHoldingJSONRequestBody
}

type CreateHoldingResponseObject interface {
	VisitCreateHoldingResponse(w http.ResponseWriter) error
}

type CreateHolding201JSONResponse Holding

func (response CreateHolding201JSONResponse) VisitCreateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHolding400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateHolding400JSONResponse) VisitCreateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHoldingRequestObject struct {
	Id string `json:"id"`
}

type DeleteHoldingResponseObject interface {
	VisitDeleteHoldingResponse(w http.ResponseWriter) error
}

type DeleteHolding200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response DeleteHolding200JSONResponse) VisitDeleteHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHolding404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteHolding404JSONResponse) VisitDeleteHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHoldingRequestObject struct {
	Id string `json:"id"`
}

type GetHoldingResponseObject interface {
	VisitGetHoldingResponse(w http.ResponseWriter) error
}

type GetHolding200JSONResponse Holding

func (response GetHolding200JSONResponse) VisitGetHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHolding404JSONResponse struct{ NotFoundJSONResponse }

func (response GetHolding404JSONResponse) VisitGetHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoldingRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateHoldingJSONRequestBody
}

type UpdateHoldingResponseObject interface {
	VisitUpdateHoldingResponse(w http.ResponseWriter) error
}

type UpdateHolding200JSONResponse Holding

func (response UpdateHolding200JSONResponse) VisitUpdateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHolding404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateHolding404JSONResponse) VisitUpdateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetForexRateRequestObject struct {
	Params GetForexRateParams
}

type GetForexRateResponseObject interface {
	VisitGetForexRateResponse(w http.ResponseWriter) error
}

type GetForexRate200JSONResponse struct {
	From *string `json:"from,omitempty"`

	// Rate 1 unit of `from` in `to`
	Rate *float64 `json:"rate,omitempty"`
	To   *string  `json:"to,omitempty"`
}

func (response GetForexRate200JSONResponse) VisitGetForexRateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMarketPriceRequestObject struct {
	Params GetMarketPriceParams
}

type GetMarketPriceResponseObject interface {
	VisitGetMarketPriceResponse(w http.ResponseWriter) error
}

type GetMarketPrice200JSONResponse struct {
	Currency *string  `json:"currency,omitempty"`
	Price    *float64 `json:"price,omitempty"`
	Symbol   *string  `json:"symbol,omitempty"`
}

func (response GetMarketPrice200JSONResponse) VisitGetMarketPriceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMarketPrice400JSONResponse struct{ BadRequestJSONResponse }

func (response GetMarketPrice400JSONResponse) VisitGetMarketPriceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMarketPrice502JSONResponse struct{ BadGatewayJSONResponse }

func (response GetMarketPrice502JSONResponse) VisitGetMarketPriceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetPricesRequestObject struct {
}

type GetPricesResponseObject interface {
	VisitGetPricesResponse(w http.ResponseWriter) error
}

type GetPrices200JSONResponse PricesResponse

func (response GetPrices200JSONResponse) VisitGetPricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSummaryRequestObject struct {
}

type GetSummaryResponseObject interface {
	VisitGetSummaryResponse(w http.ResponseWriter) error
}

type GetSummary200JSONResponse Summary

func (response GetSummary200JSONResponse) VisitGetSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all holdings
	// (GET /holdings)
	ListHoldings(ctx context.Context, request ListHoldingsRequestObject) (ListHoldingsResponseObject, error)
	// Add a new holding
	// (POST /holdings)
	CreateHolding(ctx context.Context, request CreateHoldingRequestObject) (CreateHoldingResponseObject, error)
	// Delete a holding
	// (DELETE /holdings/{id})
	DeleteHolding(ctx context.Context, request DeleteHoldingRequestObject) (DeleteHoldingResponseObject, error)
	// Get a single holding
	// (GET /holdings/{id})
	GetHolding(ctx context.Context, request GetHoldingRequestObject) (GetHoldingResponseObject, error)
	// Update a holding
	// (PUT /holdings/{id})
	UpdateHolding(ctx context.Context, request UpdateHoldingRequestObject) (UpdateHoldingResponseObject, error)
	// Get forex exchange rate
	// (GET /market/forex)
	GetForexRate(ctx context.Context, request GetForexRateRequestObject) (GetForexRateResponseObject, error)
	// Get live price for any symbol
	// (GET /market/price)
	GetMarketPrice(ctx context.Context, request GetMarketPriceRequestObject) (GetMarketPriceResponseObject, error)
	// Get all holdings enriched with live market prices
	// (GET /prices)
	GetPrices(ctx context.Context, request GetPricesRequestObject) (GetPricesResponseObject, error)
	// Portfolio-level summary with live P&L
	// (GET /summary)
	GetSummary(ctx context.Context, request GetSummaryRequestObject) (GetSummaryResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListHoldings operation middleware
func (sh *strictHandler) ListHoldings(ctx echo.Context) error {
	var request ListHoldingsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListHoldings(ctx.Request().Context(), request.(ListHoldingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHoldings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListHoldingsResponseObject); ok {
		return validResponse.VisitListHoldingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateHolding operation middleware
func (sh *strictHandler) CreateHolding(ctx echo.Context) error {
	var request CreateHoldingRequestObject

	var body CreateHoldingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateHolding(ctx.Request().Context(), request.(CreateHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateHolding")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateHoldingResponseObject); ok {
		return validResponse.VisitCreateHoldingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteHolding operation middleware
func (sh *strictHandler) DeleteHolding(ctx echo.Context, id string) error {
	var request DeleteHoldingRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteHolding(ctx.Request().Context(), request.(DeleteHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteHolding")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteHoldingResponseObject); ok {
		return validResponse.VisitDeleteHoldingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHolding operation middleware
func (sh *strictHandler) GetHolding(ctx echo.Context, id string) error {
	var request GetHoldingRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHolding(ctx.Request().Context(), request.(GetHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHolding")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHoldingResponseObject); ok {
		return validResponse.VisitGetHoldingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateHolding operation middleware
func (sh *strictHandler) UpdateHolding(ctx echo.Context, id string) error {
	var request UpdateHoldingRequestObject

	request.Id = id

	var body UpdateHoldingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateHolding(ctx.Request().Context(), request.(UpdateHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateHolding")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateHoldingResponseObject); ok {
		return validResponse.VisitUpdateHoldingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetForexRate operation middleware
func (sh *strictHandler) GetForexRate(ctx echo.Context, params GetForexRateParams) error {
	var request GetForexRateRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetForexRate(ctx.Request().Context(), request.(GetForexRateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetForexRate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetForexRateResponseObject); ok {
		return validResponse.VisitGetForexRateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMarketPrice operation middleware
func (sh *strictHandler) GetMarketPrice(ctx echo.Context, params GetMarketPriceParams) error {
	var request GetMarketPriceRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMarketPrice(ctx.Request().Context(), request.(GetMarketPriceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMarketPrice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMarketPriceResponseObject); ok {
		return validResponse.VisitGetMarketPriceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPrices operation middleware
func (sh *strictHandler) GetPrices(ctx echo.Context) error {
	var request GetPricesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPrices(ctx.Request().Context(), request.(GetPricesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPrices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPricesResponseObject); ok {
		return validResponse.VisitGetPricesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSummary operation middleware
func (sh *strictHandler) GetSummary(ctx echo.Context) error {
	var request GetSummaryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSummary(ctx.Request().Context(), request.(GetSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSummary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSummaryResponseObject); ok {
		return validResponse.VisitGetSummaryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
