// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HoldingExchange.
const (
	HoldingExchangeBSE    HoldingExchange = "BSE"
	HoldingExchangeNASDAQ HoldingExchange = "NASDAQ"
	HoldingExchangeNSE    HoldingExchange = "NSE"
	HoldingExchangeNYSE   HoldingExchange = "NYSE"
	HoldingExchangeOTHER  HoldingExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingExchange enum.
func (e HoldingExchange) Valid() bool {
	switch e {
	case HoldingExchangeBSE:
		return true
	case HoldingExchangeNASDAQ:
		return true
	case HoldingExchangeNSE:
		return true
	case HoldingExchangeNYSE:
		return true
	case HoldingExchangeOTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingType.
const (
	HoldingTypeEtf   HoldingType = "etf"
	HoldingTypeStock HoldingType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingType enum.
func (e HoldingType) Valid() bool {
	switch e {
	case HoldingTypeEtf:
		return true
	case HoldingTypeStock:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputExchange.
const (
	HoldingInputExchangeBSE    HoldingInputExchange = "BSE"
	HoldingInputExchangeNASDAQ HoldingInputExchange = "NASDAQ"
	HoldingInputExchangeNSE    HoldingInputExchange = "NSE"
	HoldingInputExchangeNYSE   HoldingInputExchange = "NYSE"
	HoldingInputExchangeOTHER  HoldingInputExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingInputExchange enum.
func (e HoldingInputExchange) Valid() bool {
	switch e {
	case HoldingInputExchangeBSE:
		return true
	case HoldingInputExchangeNASDAQ:
		return true
	case HoldingInputExchangeNSE:
		return true
	case HoldingInputExchangeNYSE:
		return true
	case HoldingInputExchangeOTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputType.
const (
	HoldingInputTypeEtf   HoldingInputType = "etf"
	HoldingInputTypeStock HoldingInputType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingInputType enum.
func (e HoldingInputType) Valid() bool {
	switch e {
	case HoldingInputTypeEtf:
		return true
	case HoldingInputTypeStock:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceExchange.
const (
	BSE    HoldingWithPriceExchange = "BSE"
	NASDAQ HoldingWithPriceExchange = "NASDAQ"
	NSE    HoldingWithPriceExchange = "NSE"
	NYSE   HoldingWithPriceExchange = "NYSE"
	OTHER  HoldingWithPriceExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceExchange enum.
func (e HoldingWithPriceExchange) Valid() bool {
	switch e {
	case BSE:
		return true
	case NASDAQ:
		return true
	case NSE:
		return true
	case NYSE:
		return true
	case OTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceType.
const (
	Etf   HoldingWithPriceType = "etf"
	Stock HoldingWithPriceType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceType enum.
func (e HoldingWithPriceType) Valid() bool {
	switch e {
	case Etf:
		return true
	case Stock:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// Holding defines model for Holding.
type Holding struct {
	// AvgCostPrice Average purchase price per share (INR for Indian stocks)
	AvgCostPrice *float64         `json:"avg_cost_price,omitempty"`
	CreatedAt    *time.Time       `json:"created_at,omitempty"`
	Exchange     *HoldingExchange `json:"exchange,omitempty"`

	// Id MongoDB ObjectID
	Id    *string `json:"id,omitempty"`
	Notes *string `json:"notes,omitempty"`

	// RealizedPnl Profit/loss from shares already sold
	RealizedPnl *float64 `json:"realized_pnl,omitempty"`

	// Script Display name (e.g. "TCS", "GOLD BEES")
	Script *string `json:"script,omitempty"`

	// StocksOwned Current quantity held
	StocksOwned *float64 `json:"stocks_owned,omitempty"`

	// Symbol Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL")
	Symbol    *string      `json:"symbol,omitempty"`
	Type      *HoldingType `json:"type,omitempty"`
	UpdatedAt *time.Time   `json:"updated_at,omitempty"`
}

// HoldingExchange defines model for Holding.Exchange.
type HoldingExchange string

// HoldingType defines model for Holding.Type.
type HoldingType string

// HoldingInput defines model for HoldingInput.
type HoldingInput struct {
	AvgCostPrice *float64             `json:"avg_cost_price,omitempty"`
	Exchange     HoldingInputExchange `json:"exchange"`
	Notes        *string              `json:"notes,omitempty"`
	RealizedPnl  *float64             `json:"realized_pnl,omitempty"`
	Script       string               `json:"script"`
	StocksOwned  *float64             `json:"stocks_owned,omitempty"`
	Symbol       *string              `json:"symbol,omitempty"`
	Type         HoldingInputType     `json:"type"`
}

// HoldingInputExchange defines model for HoldingInput.Exchange.
type HoldingInputExchange string

// HoldingInputType defines model for HoldingInput.Type.
type HoldingInputType string

// HoldingWithPrice defines model for HoldingWithPrice.
type HoldingWithPrice struct {
	// AvgCostPrice Average purchase price per share (INR for Indian stocks)
	AvgCostPrice *float64 `json:"avg_cost_price,omitempty"`

	// CostPrice stocks_owned × avg_cost_price
	CostPrice    *float64   `json:"cost_price,omitempty"`
	CostPriceEur *float64   `json:"cost_price_eur,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	CurrentPrice *float64   `json:"current_price,omitempty"`

	// CurrentValue stocks_owned × current_price
	CurrentValue    *float64                  `json:"current_value,omitempty"`
	CurrentValueEur *float64                  `json:"current_value_eur,omitempty"`
	Exchange        *HoldingWithPriceExchange `json:"exchange,omitempty"`

	// Id MongoDB ObjectID
	Id         *string `json:"id,omitempty"`
	Notes      *string `json:"notes,omitempty"`
	PriceError *string `json:"price_error,omitempty"`

	// RealizedPnl Profit/loss from shares already sold
	RealizedPnl    *float64 `json:"realized_pnl,omitempty"`
	RealizedPnlEur *float64 `json:"realized_pnl_eur,omitempty"`

	// Script Display name (e.g. "TCS", "GOLD BEES")
	Script *string `json:"script,omitempty"`

	// StocksOwned Current quantity held
	StocksOwned *float64 `json:"stocks_owned,omitempty"`

	// Symbol Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL")
	Symbol *string               `json:"symbol,omitempty"`
	Type   *HoldingWithPriceType `json:"type,omitempty"`

	// UnrealizedPnl current_value − cost_price
	UnrealizedPnl    *float64   `json:"unrealized_pnl,omitempty"`
	UnrealizedPnlEur *float64   `json:"unrealized_pnl_eur,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
}

// HoldingWithPriceExchange defines model for HoldingWithPrice.Exchange.
type HoldingWithPriceExchange string

// HoldingWithPriceType defines model for HoldingWithPrice.Type.
type HoldingWithPriceType string

// PricesResponse defines model for PricesResponse.
type PricesResponse struct {
	// EurRate Live INR→EUR rate used for conversions
	EurRate  *float64            `json:"eur_rate,omitempty"`
	Holdings *[]HoldingWithPrice `json:"holdings,omitempty"`
}

// Summary defines model for Summary.
type Summary struct {
	EurRate              *float64 `json:"eur_rate,omitempty"`
	TotalCost            *float64 `json:"total_cost,omitempty"`
	TotalCostEur         *float64 `json:"total_cost_eur,omitempty"`
	TotalCurrentValue    *float64 `json:"total_current_value,omitempty"`
	TotalCurrentValueEur *float64 `json:"total_current_value_eur,omitempty"`
	TotalRealized        *float64 `json:"total_realized,omitempty"`
	TotalRealizedEur     *float64 `json:"total_realized_eur,omitempty"`
	TotalUnrealized      *float64 `json:"total_unrealized,omitempty"`
	TotalUnrealizedEur   *float64 `json:"total_unrealized_eur,omitempty"`
}

// BadGateway defines model for BadGateway.
type BadGateway = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// GetForexRateParams defines parameters for GetForexRate.
type GetForexRateParams struct {
	From *string `form:"from,omitempty" json:"from,omitempty"`
	To   *string `form:"to,omitempty" json:"to,omitempty"`
}

// GetMarketPriceParams defines parameters for GetMarketPrice.
type GetMarketPriceParams struct {
	// Symbol Yahoo Finance ticker (e.g. TCS.NS, AAPL, GOLDBEES.NS)
	Symbol string `form:"symbol" json:"symbol"`
}

// CreateHoldingJSONRequestBody defines body for CreateHolding for application/json ContentType.
type CreateHoldingJSONRequestBody = HoldingInput

// UpdateHoldingJSONRequestBody defines body for UpdateHolding for application/json ContentType.
type UpdateHoldingJSONRequestBody = HoldingInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all holdings
	// (GET /holdings)
	ListHoldings(w http.ResponseWriter, r *http.Request)
	// Add a new holding
	// (POST /holdings)
	CreateHolding(w http.ResponseWriter, r *http.Request)
	// Delete a holding
	// (DELETE /holdings/{id})
	DeleteHolding(w http.ResponseWriter, r *http.Request, id string)
	// Get a single holding
	// (GET /holdings/{id})
	GetHolding(w http.ResponseWriter, r *http.Request, id string)
	// Update a holding
	// (PUT /holdings/{id})
	UpdateHolding(w http.ResponseWriter, r *http.Request, id string)
	// Get forex exchange rate
	// (GET /market/forex)
	GetForexRate(w http.ResponseWriter, r *http.Request, params GetForexRateParams)
	// Get live price for any symbol
	// (GET /market/price)
	GetMarketPrice(w http.ResponseWriter, r *http.Request, params GetMarketPriceParams)
	// Get all holdings enriched with live market prices
	// (GET /prices)
	GetPrices(w http.ResponseWriter, r *http.Request)
	// Portfolio-level summary with live P&L
	// (GET /summary)
	GetSummary(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all holdings
// (GET /holdings)
func (_ Unimplemented) ListHoldings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new holding
// (POST /holdings)
func (_ Unimplemented) CreateHolding(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a holding
// (DELETE /holdings/{id})
func (_ Unimplemented) DeleteHolding(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a single holding
// (GET /holdings/{id})
func (_ Unimplemented) GetHolding(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a holding
// (PUT /holdings/{id})
func (_ Unimplemented) UpdateHolding(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get forex exchange rate
// (GET /market/forex)
func (_ Unimplemented) GetForexRate(w http.ResponseWriter, r *http.Request, params GetForexRateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get live price for any symbol
// (GET /market/price)
func (_ Unimplemented) GetMarketPrice(w http.ResponseWriter, r *http.Request, params GetMarketPriceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all holdings enriched with live market prices
// (GET /prices)
func (_ Unimplemented) GetPrices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Portfolio-level summary with live P&L
// (GET /summary)
func (_ Unimplemented) GetSummary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListHoldings operation middleware
func (siw *ServerInterfaceWrapper) ListHoldings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHoldings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateHolding operation middleware
func (siw *ServerInterfaceWrapper) CreateHolding(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateHolding(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteHolding operation middleware
func (siw *ServerInterfaceWrapper) DeleteHolding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteHolding(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHolding operation middleware
func (siw *ServerInterfaceWrapper) GetHolding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHolding(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateHolding operation middleware
func (siw *ServerInterfaceWrapper) UpdateHolding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateHolding(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetForexRate operation middleware
func (siw *ServerInterfaceWrapper) GetForexRate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetForexRateParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetForexRate(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMarketPrice operation middleware
func (siw *ServerInterfaceWrapper) GetMarketPrice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMarketPriceParams

	// ------------- Required query parameter "symbol" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "symbol", r.URL.Query(), &params.Symbol, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "symbol"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "symbol", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMarketPrice(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPrices operation middleware
func (siw *ServerInterfaceWrapper) GetPrices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSummary operation middleware
func (siw *ServerInterfaceWrapper) GetSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/holdings", wrapper.ListHoldings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/holdings", wrapper.CreateHolding)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/holdings/{id}", wrapper.DeleteHolding)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/holdings/{id}", wrapper.GetHolding)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/holdings/{id}", wrapper.UpdateHolding)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/market/forex", wrapper.GetForexRate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/market/price", wrapper.GetMarketPrice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/prices", wrapper.GetPrices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/summary", wrapper.GetSummary)
	})

	return r
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type ListHoldingsRequestObject struct {
}

type ListHoldingsResponseObject interface {
	VisitListHoldingsResponse(w http.ResponseWriter) error
}

type ListHoldings200JSONResponse []Holding

func (response ListHoldings200JSONResponse) VisitListHoldingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHoldingRequestObject struct {
	Body *CreateHoldingJSONRequestBody
}

type CreateHoldingResponseObject interface {
	VisitCreateHoldingResponse(w http.ResponseWriter) error
}

type CreateHolding201JSONResponse Holding

func (response CreateHolding201JSONResponse) VisitCreateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHolding400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateHolding400JSONResponse) VisitCreateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHoldingRequestObject struct {
	Id string `json:"id"`
}

type DeleteHoldingResponseObject interface {
	VisitDeleteHoldingResponse(w http.ResponseWriter) error
}

type DeleteHolding200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response DeleteHolding200JSONResponse) VisitDeleteHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHolding404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteHolding404JSONResponse) VisitDeleteHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHoldingRequestObject struct {
	Id string `json:"id"`
}

type GetHoldingResponseObject interface {
	VisitGetHoldingResponse(w http.ResponseWriter) error
}

type GetHolding200JSONResponse Holding

func (response GetHolding200JSONResponse) VisitGetHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHolding404JSONResponse struct{ NotFoundJSONResponse }

func (response GetHolding404JSONResponse) VisitGetHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoldingRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateHoldingJSONRequestBody
}

type UpdateHoldingResponseObject interface {
	VisitUpdateHoldingResponse(w http.ResponseWriter) error
}

type UpdateHolding200JSONResponse Holding

func (response UpdateHolding200JSONResponse) VisitUpdateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHolding404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateHolding404JSONResponse) VisitUpdateHoldingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetForexRateRequestObject struct {
	Params GetForexRateParams
}

type GetForexRateResponseObject interface {
	VisitGetForexRateResponse(w http.ResponseWriter) error
}

type GetForexRate200JSONResponse struct {
	From *string `json:"from,omitempty"`

	// Rate 1 unit of `from` in `to`
	Rate *float64 `json:"rate,omitempty"`
	To   *string  `json:"to,omitempty"`
}

func (response GetForexRate200JSONResponse) VisitGetForexRateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMarketPriceRequestObject struct {
	Params GetMarketPriceParams
}

type GetMarketPriceResponseObject interface {
	VisitGetMarketPriceResponse(w http.ResponseWriter) error
}

type GetMarketPrice200JSONResponse struct {
	Currency *string  `json:"currency,omitempty"`
	Price    *float64 `json:"price,omitempty"`
	Symbol   *string  `json:"symbol,omitempty"`
}

func (response GetMarketPrice200JSONResponse) VisitGetMarketPriceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMarketPrice400JSONResponse struct{ BadRequestJSONResponse }

func (response GetMarketPrice400JSONResponse) VisitGetMarketPriceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMarketPrice502JSONResponse struct{ BadGatewayJSONResponse }

func (response GetMarketPrice502JSONResponse) VisitGetMarketPriceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetPricesRequestObject struct {
}

type GetPricesResponseObject interface {
	VisitGetPricesResponse(w http.ResponseWriter) error
}

type GetPrices200JSONResponse PricesResponse

func (response GetPrices200JSONResponse) VisitGetPricesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSummaryRequestObject struct {
}

type GetSummaryResponseObject interface {
	VisitGetSummaryResponse(w http.ResponseWriter) error
}

type GetSummary200JSONResponse Summary

func (response GetSummary200JSONResponse) VisitGetSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all holdings
	// (GET /holdings)
	ListHoldings(ctx context.Context, request ListHoldingsRequestObject) (ListHoldingsResponseObject, error)
	// Add a new holding
	// (POST /holdings)
	CreateHolding(ctx context.Context, request CreateHoldingRequestObject) (CreateHoldingResponseObject, error)
	// Delete a holding
	// (DELETE /holdings/{id})
	DeleteHolding(ctx context.Context, request DeleteHoldingRequestObject) (DeleteHoldingResponseObject, error)
	// Get a single holding
	// (GET /holdings/{id})
	GetHolding(ctx context.Context, request GetHoldingRequestObject) (GetHoldingResponseObject, error)
	// Update a holding
	// (PUT /holdings/{id})
	UpdateHolding(ctx context.Context, request UpdateHoldingRequestObject) (UpdateHoldingResponseObject, error)
	// Get forex exchange rate
	// (GET /market/forex)
	GetForexRate(ctx context.Context, request GetForexRateRequestObject) (GetForexRateResponseObject, error)
	// Get live price for any symbol
	// (GET /market/price)
	GetMarketPrice(ctx context.Context, request GetMarketPriceRequestObject) (GetMarketPriceResponseObject, error)
	// Get all holdings enriched with live market prices
	// (GET /prices)
	GetPrices(ctx context.Context, request GetPricesRequestObject) (GetPricesResponseObject, error)
	// Portfolio-level summary with live P&L
	// (GET /summary)
	GetSummary(ctx context.Context, request GetSummaryRequestObject) (GetSummaryResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListHoldings operation middleware
func (sh *strictHandler) ListHoldings(w http.ResponseWriter, r *http.Request) {
	var request ListHoldingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListHoldings(ctx, request.(ListHoldingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHoldings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListHoldingsResponseObject); ok {
		if err := validResponse.VisitListHoldingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateHolding operation middleware
func (sh *strictHandler) CreateHolding(w http.ResponseWriter, r *http.Request) {
	var request CreateHoldingRequestObject

	var body CreateHoldingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateHolding(ctx, request.(CreateHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateHolding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateHoldingResponseObject); ok {
		if err := validResponse.VisitCreateHoldingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteHolding operation middleware
func (sh *strictHandler) DeleteHolding(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteHoldingRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteHolding(ctx, request.(DeleteHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteHolding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteHoldingResponseObject); ok {
		if err := validResponse.VisitDeleteHoldingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHolding operation middleware
func (sh *strictHandler) GetHolding(w http.ResponseWriter, r *http.Request, id string) {
	var request GetHoldingRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHolding(ctx, request.(GetHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHolding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHoldingResponseObject); ok {
		if err := validResponse.VisitGetHoldingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateHolding operation middleware
func (sh *strictHandler) UpdateHolding(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateHoldingRequestObject

	request.Id = id

	var body UpdateHoldingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateHolding(ctx, request.(UpdateHoldingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateHolding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateHoldingResponseObject); ok {
		if err := validResponse.VisitUpdateHoldingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetForexRate operation middleware
func (sh *strictHandler) GetForexRate(w http.ResponseWriter, r *http.Request, params GetForexRateParams) {
	var request GetForexRateRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetForexRate(ctx, request.(GetForexRateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetForexRate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetForexRateResponseObject); ok {
		if err := validResponse.VisitGetForexRateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMarketPrice operation middleware
func (sh *strictHandler) GetMarketPrice(w http.ResponseWriter, r *http.Request, params GetMarketPriceParams) {
	var request GetMarketPriceRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMarketPrice(ctx, request.(GetMarketPriceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMarketPrice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMarketPriceResponseObject); ok {
		if err := validResponse.VisitGetMarketPriceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPrices operation middleware
func (sh *strictHandler) GetPrices(w http.ResponseWriter, r *http.Request) {
	var request GetPricesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPrices(ctx, request.(GetPricesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPrices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPricesResponseObject); ok {
		if err := validResponse.VisitGetPricesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSummary operation middleware
func (sh *strictHandler) GetSummary(w http.ResponseWriter, r *http.Request) {
	var request GetSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSummary(ctx, request.(GetSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSummaryResponseObject); ok {
		if err := validResponse.VisitGetSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
