// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HistoryRegionSnapshotSource.
const (
	Cron   HistoryRegionSnapshotSource = "cron"
	Manual HistoryRegionSnapshotSource = "manual"
)

// Valid indicates whether the value is a known member of the HistoryRegionSnapshotSource enum.
func (e HistoryRegionSnapshotSource) Valid() bool {
	switch e {
	case Cron:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for HoldingCurrency.
const (
	HoldingCurrencyEUR HoldingCurrency = "EUR"
	HoldingCurrencyINR HoldingCurrency = "INR"
)

// Valid indicates whether the value is a known member of the HoldingCurrency enum.
func (e HoldingCurrency) Valid() bool {
	switch e {
	case HoldingCurrencyEUR:
		return true
	case HoldingCurrencyINR:
		return true
	default:
		return false
	}
}

// Defines values for HoldingExchange.
const (
	HoldingExchangeBSE    HoldingExchange = "BSE"
	HoldingExchangeNASDAQ HoldingExchange = "NASDAQ"
	HoldingExchangeNSE    HoldingExchange = "NSE"
	HoldingExchangeNYSE   HoldingExchange = "NYSE"
	HoldingExchangeOTHER  HoldingExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingExchange enum.
func (e HoldingExchange) Valid() bool {
	switch e {
	case HoldingExchangeBSE:
		return true
	case HoldingExchangeNASDAQ:
		return true
	case HoldingExchangeNSE:
		return true
	case HoldingExchangeNYSE:
		return true
	case HoldingExchangeOTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingType.
const (
	HoldingTypeEtf   HoldingType = "etf"
	HoldingTypeStock HoldingType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingType enum.
func (e HoldingType) Valid() bool {
	switch e {
	case HoldingTypeEtf:
		return true
	case HoldingTypeStock:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputCurrency.
const (
	HoldingInputCurrencyEUR HoldingInputCurrency = "EUR"
	HoldingInputCurrencyINR HoldingInputCurrency = "INR"
)

// Valid indicates whether the value is a known member of the HoldingInputCurrency enum.
func (e HoldingInputCurrency) Valid() bool {
	switch e {
	case HoldingInputCurrencyEUR:
		return true
	case HoldingInputCurrencyINR:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputExchange.
const (
	HoldingInputExchangeBSE    HoldingInputExchange = "BSE"
	HoldingInputExchangeNASDAQ HoldingInputExchange = "NASDAQ"
	HoldingInputExchangeNSE    HoldingInputExchange = "NSE"
	HoldingInputExchangeNYSE   HoldingInputExchange = "NYSE"
	HoldingInputExchangeOTHER  HoldingInputExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingInputExchange enum.
func (e HoldingInputExchange) Valid() bool {
	switch e {
	case HoldingInputExchangeBSE:
		return true
	case HoldingInputExchangeNASDAQ:
		return true
	case HoldingInputExchangeNSE:
		return true
	case HoldingInputExchangeNYSE:
		return true
	case HoldingInputExchangeOTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingInputType.
const (
	HoldingInputTypeEtf   HoldingInputType = "etf"
	HoldingInputTypeStock HoldingInputType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingInputType enum.
func (e HoldingInputType) Valid() bool {
	switch e {
	case HoldingInputTypeEtf:
		return true
	case HoldingInputTypeStock:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceCurrency.
const (
	HoldingWithPriceCurrencyEUR HoldingWithPriceCurrency = "EUR"
	HoldingWithPriceCurrencyINR HoldingWithPriceCurrency = "INR"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceCurrency enum.
func (e HoldingWithPriceCurrency) Valid() bool {
	switch e {
	case HoldingWithPriceCurrencyEUR:
		return true
	case HoldingWithPriceCurrencyINR:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceExchange.
const (
	BSE    HoldingWithPriceExchange = "BSE"
	NASDAQ HoldingWithPriceExchange = "NASDAQ"
	NSE    HoldingWithPriceExchange = "NSE"
	NYSE   HoldingWithPriceExchange = "NYSE"
	OTHER  HoldingWithPriceExchange = "OTHER"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceExchange enum.
func (e HoldingWithPriceExchange) Valid() bool {
	switch e {
	case BSE:
		return true
	case NASDAQ:
		return true
	case NSE:
		return true
	case NYSE:
		return true
	case OTHER:
		return true
	default:
		return false
	}
}

// Defines values for HoldingWithPriceType.
const (
	Etf   HoldingWithPriceType = "etf"
	Stock HoldingWithPriceType = "stock"
)

// Valid indicates whether the value is a known member of the HoldingWithPriceType enum.
func (e HoldingWithPriceType) Valid() bool {
	switch e {
	case Etf:
		return true
	case Stock:
		return true
	default:
		return false
	}
}

// Defines values for TransactionCurrency.
const (
	TransactionCurrencyEUR TransactionCurrency = "EUR"
	TransactionCurrencyINR TransactionCurrency = "INR"
)

// Valid indicates whether the value is a known member of the TransactionCurrency enum.
func (e TransactionCurrency) Valid() bool {
	switch e {
	case TransactionCurrencyEUR:
		return true
	case TransactionCurrencyINR:
		return true
	default:
		return false
	}
}

// Defines values for TransactionType.
const (
	TransactionTypeBonus    TransactionType = "bonus"
	TransactionTypeBuy      TransactionType = "buy"
	TransactionTypeDividend TransactionType = "dividend"
	TransactionTypeMerger   TransactionType = "merger"
	TransactionTypeOpening  TransactionType = "opening"
	TransactionTypeSell     TransactionType = "sell"
	TransactionTypeSplit    TransactionType = "split"
)

// Valid indicates whether the value is a known member of the TransactionType enum.
func (e TransactionType) Valid() bool {
	switch e {
	case TransactionTypeBonus:
		return true
	case TransactionTypeBuy:
		return true
	case TransactionTypeDividend:
		return true
	case TransactionTypeMerger:
		return true
	case TransactionTypeOpening:
		return true
	case TransactionTypeSell:
		return true
	case TransactionTypeSplit:
		return true
	default:
		return false
	}
}

// Defines values for TransactionInputType.
const (
	TransactionInputTypeBonus    TransactionInputType = "bonus"
	TransactionInputTypeBuy      TransactionInputType = "buy"
	TransactionInputTypeDividend TransactionInputType = "dividend"
	TransactionInputTypeMerger   TransactionInputType = "merger"
	TransactionInputTypeOpening  TransactionInputType = "opening"
	TransactionInputTypeSell     TransactionInputType = "sell"
	TransactionInputTypeSplit    TransactionInputType = "split"
)

// Valid indicates whether the value is a known member of the TransactionInputType enum.
func (e TransactionInputType) Valid() bool {
	switch e {
	case TransactionInputTypeBonus:
		return true
	case TransactionInputTypeBuy:
		return true
	case TransactionInputTypeDividend:
		return true
	case TransactionInputTypeMerger:
		return true
	case TransactionInputTypeOpening:
		return true
	case TransactionInputTypeSell:
		return true
	case TransactionInputTypeSplit:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleSuperadmin UserRole = "superadmin"
	UserRoleUser       UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleSuperadmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// AddHistoryRowInput defines model for AddHistoryRowInput.
type AddHistoryRowInput struct {
	Date    openapi_types.Date            `json:"date"`
	Regions map[string]HistoryRegionInput `json:"regions"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CurrencyChange defines model for CurrencyChange.
type CurrencyChange struct {
	ChangePct   *float64 `json:"change_pct,omitempty"`
	ChangeValue *float64 `json:"change_value,omitempty"`

	// Currency INR | EUR | USD
	Currency *string `json:"currency,omitempty"`

	// Current Today's live current value in the native currency.
	Current *float64 `json:"current,omitempty"`

	// PreviousClose Snapshot current value in the native currency.
	PreviousClose *float64 `json:"previous_close,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// GoldMissingDates Calendar days between the first gold purchase and today that have
// no price row — the Gold page's blocking prompt (PRD-003 §7).
type GoldMissingDates struct {
	Missing []openapi_types.Date `json:"missing"`
}

// GoldPrice One user-entered daily per-gram gold price (PRD-003 §7).
type GoldPrice struct {
	Date openapi_types.Date `json:"date"`

	// PricePerGram Per-gram rate for that calendar day (> 0)
	PricePerGram float64 `json:"price_per_gram"`
}

// GoldToggleRequest defines model for GoldToggleRequest.
type GoldToggleRequest struct {
	// Enabled Turn gold tracking on or off for the account
	Enabled bool `json:"enabled"`
}

// GoldTransaction One gold purchase with the derived columns (PRD-003 §5).
type GoldTransaction struct {
	ActualPaid   float64            `json:"actual_paid"`
	BillAmount   *float64           `json:"bill_amount,omitempty"`
	BilledWeight *float64           `json:"billed_weight,omitempty"`
	ChennaiRate  *float64           `json:"chennai_rate,omitempty"`
	Date         openapi_types.Date `json:"date"`
	GmPrice      float64            `json:"gm_price"`

	// GoldCost gm_price × grams_bought
	GoldCost    float64 `json:"gold_cost"`
	GramsBought float64 `json:"grams_bought"`

	// GstOnCost 3% of gold_cost
	GstOnCost float64 `json:"gst_on_cost"`

	// GstOnQuote 3% of quote_price; null when no quote recorded
	GstOnQuote *float64 `json:"gst_on_quote,omitempty"`
	Id         int64    `json:"id"`

	// NettPerGram actual_paid ÷ grams_bought
	NettPerGram float64 `json:"nett_per_gram"`

	// NettReduction bill_amount − actual_paid; null when no bill recorded
	NettReduction *float64 `json:"nett_reduction,omitempty"`

	// NimmiLoss actual_paid − gold_cost (spreadsheet J − D)
	NimmiLoss  float64  `json:"nimmi_loss"`
	QuotePrice *float64 `json:"quote_price,omitempty"`

	// TotalExpected gold_cost + gst_on_cost
	TotalExpected float64 `json:"total_expected"`
}

// GoldTransactionInput Entered fields of one physical gold purchase (PRD-003 §5). Every
// computed column is derived server-side; clients never send them.
type GoldTransactionInput struct {
	// ActualPaid Cash actually paid (>= 0)
	ActualPaid float64 `json:"actual_paid"`

	// BillAmount Amount printed on the bill
	BillAmount *float64 `json:"bill_amount,omitempty"`

	// BilledWeight Grams on the bill (can differ from actual)
	BilledWeight *float64 `json:"billed_weight,omitempty"`

	// ChennaiRate Market reference rate that day
	ChennaiRate *float64 `json:"chennai_rate,omitempty"`

	// Date Purchase date
	Date openapi_types.Date `json:"date"`

	// GmPrice Per-gram rate for this purchase (> 0)
	GmPrice float64 `json:"gm_price"`

	// GramsBought Grams actually bought (> 0)
	GramsBought float64 `json:"grams_bought"`

	// QuotePrice Per-gram rate the jeweler quoted
	QuotePrice *float64 `json:"quote_price,omitempty"`
}

// HistoryConflictResponse defines model for HistoryConflictResponse.
type HistoryConflictResponse struct {
	Conflicts []struct {
		Existing HistoryRegionSnapshot `json:"existing"`
		Incoming HistoryRegionInput    `json:"incoming"`
		Region   string                `json:"region"`
	} `json:"conflicts"`
	Error string `json:"error"`
}

// HistoryDateConflict defines model for HistoryDateConflict.
type HistoryDateConflict struct {
	Date     openapi_types.Date               `json:"date"`
	Existing map[string]HistoryRegionSnapshot `json:"existing"`
	Incoming map[string]HistoryRegionInput    `json:"incoming"`
}

// HistoryHolding One stock's line within a history snapshot (cron rows only).
type HistoryHolding struct {
	// ClosePrice Close price on price_date (the row's current price)
	ClosePrice float64 `json:"close_price"`

	// Currency Bucket currency code (INR|EUR|USD)
	Currency string `json:"currency"`

	// Current quantity × close_price
	Current *float64 `json:"current,omitempty"`

	// PriceDate Trading date the close_price belongs to (YYYY-MM-DD)
	PriceDate *string `json:"price_date,omitempty"`
	Quantity  float64 `json:"quantity"`
	Script    string  `json:"script"`
	Symbol    string  `json:"symbol"`
}

// HistoryList defines model for HistoryList.
type HistoryList struct {
	Currency string       `json:"currency"`
	Rows     []HistoryRow `json:"rows"`
}

// HistoryRegionInput defines model for HistoryRegionInput.
type HistoryRegionInput struct {
	Current  float64 `json:"current"`
	Invested float64 `json:"invested"`
}

// HistoryRegionSnapshot defines model for HistoryRegionSnapshot.
type HistoryRegionSnapshot struct {
	Current             float64  `json:"current"`
	Invested            float64  `json:"invested"`
	OriginalCronCurrent *float64 `json:"original_cron_current,omitempty"`

	// OriginalCronInvested Pre-override cron value (audit anchor; PD-042 §3.3).
	OriginalCronInvested *float64                    `json:"original_cron_invested,omitempty"`
	Source               HistoryRegionSnapshotSource `json:"source"`

	// WriteCurrency Currency code (INR|EUR|USD) the manual amount was typed in. Empty on cron-written buckets.
	WriteCurrency *string `json:"write_currency,omitempty"`
}

// HistoryRegionSnapshotSource defines model for HistoryRegionSnapshot.Source.
type HistoryRegionSnapshotSource string

// HistoryRow defines model for HistoryRow.
type HistoryRow struct {
	Date openapi_types.Date `json:"date"`

	// Holdings Per-stock breakdown for cron-sourced rows; absent on manual-only rows.
	Holdings *[]HistoryHolding                `json:"holdings,omitempty"`
	Regions  map[string]HistoryRegionSnapshot `json:"regions"`
	Totals   HistoryTotals                    `json:"totals"`
}

// HistoryTotals defines model for HistoryTotals.
type HistoryTotals struct {
	CurrentTotal  float64 `json:"current_total"`
	InvestedTotal float64 `json:"invested_total"`

	// PnlPct Null when invested_total is zero (divide-by-zero).
	PnlPct *float64 `json:"pnl_pct,omitempty"`
}

// Holding defines model for Holding.
type Holding struct {
	// AvgCostPrice Average purchase price per share in the holding's currency
	AvgCostPrice *float64   `json:"avg_cost_price,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`

	// Currency Currency in which avg_cost_price and realized_pnl are denominated
	Currency *HoldingCurrency `json:"currency,omitempty"`
	Exchange *HoldingExchange `json:"exchange,omitempty"`

	// HasOpening Whether an opening-balance event seeds this holding (drives the opening-date prompt)
	HasOpening *bool `json:"has_opening,omitempty"`

	// Id MongoDB ObjectID
	Id    *string `json:"id,omitempty"`
	Notes *string `json:"notes,omitempty"`

	// OpeningDate User-set effective date of the opening balance; null when not yet set
	OpeningDate *openapi_types.Date `json:"opening_date,omitempty"`

	// RealizedPnl Profit/loss from shares already sold, in the holding's currency (derived, average cost)
	RealizedPnl *float64 `json:"realized_pnl,omitempty"`

	// Script Display name (e.g. "TCS", "GOLD BEES")
	Script *string `json:"script,omitempty"`

	// StocksOwned Current quantity held
	StocksOwned *float64 `json:"stocks_owned,omitempty"`

	// Symbol Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL")
	Symbol *string `json:"symbol,omitempty"`

	// TotalDividends Cumulative cash dividend income, in the holding's currency (derived)
	TotalDividends *float64     `json:"total_dividends,omitempty"`
	Type           *HoldingType `json:"type,omitempty"`
	UpdatedAt      *time.Time   `json:"updated_at,omitempty"`
}

// HoldingCurrency Currency in which avg_cost_price and realized_pnl are denominated
type HoldingCurrency string

// HoldingExchange defines model for Holding.Exchange.
type HoldingExchange string

// HoldingType defines model for Holding.Type.
type HoldingType string

// HoldingInput defines model for HoldingInput.
type HoldingInput struct {
	AvgCostPrice *float64 `json:"avg_cost_price,omitempty"`

	// Currency Currency in which avg_cost_price and realized_pnl are denominated
	Currency *HoldingInputCurrency `json:"currency,omitempty"`
	Exchange HoldingInputExchange  `json:"exchange"`
	Notes    *string               `json:"notes,omitempty"`

	// OpeningDate Effective date of the opening balance; sets the holding's opening event date when provided
	OpeningDate *openapi_types.Date `json:"opening_date,omitempty"`

	// RealizedPnl Opening realized P&L seed (legacy carry); new sells derive this from the ledger
	RealizedPnl *float64         `json:"realized_pnl,omitempty"`
	Script      string           `json:"script"`
	StocksOwned *float64         `json:"stocks_owned,omitempty"`
	Symbol      *string          `json:"symbol,omitempty"`
	Type        HoldingInputType `json:"type"`
}

// HoldingInputCurrency Currency in which avg_cost_price and realized_pnl are denominated
type HoldingInputCurrency string

// HoldingInputExchange defines model for HoldingInput.Exchange.
type HoldingInputExchange string

// HoldingInputType defines model for HoldingInput.Type.
type HoldingInputType string

// HoldingWithPrice defines model for HoldingWithPrice.
type HoldingWithPrice struct {
	// AvgCostPrice Average purchase price per share in the holding's currency
	AvgCostPrice *float64 `json:"avg_cost_price,omitempty"`

	// CostPrice stocks_owned × avg_cost_price
	CostPrice    *float64   `json:"cost_price,omitempty"`
	CostPriceEur *float64   `json:"cost_price_eur,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`

	// Currency Currency in which avg_cost_price and realized_pnl are denominated
	Currency     *HoldingWithPriceCurrency `json:"currency,omitempty"`
	CurrentPrice *float64                  `json:"current_price,omitempty"`

	// CurrentValue stocks_owned × current_price
	CurrentValue    *float64                  `json:"current_value,omitempty"`
	CurrentValueEur *float64                  `json:"current_value_eur,omitempty"`
	Exchange        *HoldingWithPriceExchange `json:"exchange,omitempty"`

	// HasOpening Whether an opening-balance event seeds this holding (drives the opening-date prompt)
	HasOpening *bool `json:"has_opening,omitempty"`

	// Id MongoDB ObjectID
	Id    *string `json:"id,omitempty"`
	Notes *string `json:"notes,omitempty"`

	// OpeningDate User-set effective date of the opening balance; null when not yet set
	OpeningDate *openapi_types.Date `json:"opening_date,omitempty"`
	PriceError  *string             `json:"price_error,omitempty"`

	// RealizedPnl Profit/loss from shares already sold, in the holding's currency (derived, average cost)
	RealizedPnl    *float64 `json:"realized_pnl,omitempty"`
	RealizedPnlEur *float64 `json:"realized_pnl_eur,omitempty"`

	// Script Display name (e.g. "TCS", "GOLD BEES")
	Script *string `json:"script,omitempty"`

	// StocksOwned Current quantity held
	StocksOwned *float64 `json:"stocks_owned,omitempty"`

	// Symbol Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL")
	Symbol *string `json:"symbol,omitempty"`

	// TotalDividends Cumulative cash dividend income, in the holding's currency (derived)
	TotalDividends *float64              `json:"total_dividends,omitempty"`
	Type           *HoldingWithPriceType `json:"type,omitempty"`

	// UnrealizedPnl current_value − cost_price
	UnrealizedPnl    *float64   `json:"unrealized_pnl,omitempty"`
	UnrealizedPnlEur *float64   `json:"unrealized_pnl_eur,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
}

// HoldingWithPriceCurrency Currency in which avg_cost_price and realized_pnl are denominated
type HoldingWithPriceCurrency string

// HoldingWithPriceExchange defines model for HoldingWithPrice.Exchange.
type HoldingWithPriceExchange string

// HoldingWithPriceType defines model for HoldingWithPrice.Type.
type HoldingWithPriceType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// OnboardingRequest defines model for OnboardingRequest.
type OnboardingRequest struct {
	CurrentPassword string                `json:"current_password"`
	NewPassword     string                `json:"new_password"`
	SecurityAnswers []SecurityAnswerInput `json:"security_answers"`
}

// PasteHistoryInput defines model for PasteHistoryInput.
type PasteHistoryInput struct {
	// Month YYYY-MM
	Month string               `json:"month"`
	Rows  []AddHistoryRowInput `json:"rows"`
}

// PasteHistoryReport defines model for PasteHistoryReport.
type PasteHistoryReport struct {
	Applied   []openapi_types.Date  `json:"applied"`
	Conflicts []HistoryDateConflict `json:"conflicts"`
	Rejected  []RejectedPasteRow    `json:"rejected"`
}

// PatchHistoryRegionsInput defines model for PatchHistoryRegionsInput.
type PatchHistoryRegionsInput struct {
	Regions map[string]HistoryRegionInput `json:"regions"`
}

// PricesResponse defines model for PricesResponse.
type PricesResponse struct {
	// EurRate Live INR→EUR rate used for conversions
	EurRate  *float64            `json:"eur_rate,omitempty"`
	Holdings *[]HoldingWithPrice `json:"holdings,omitempty"`
}

// RecoverQuestionsRequest defines model for RecoverQuestionsRequest.
type RecoverQuestionsRequest struct {
	Username string `json:"username"`
}

// RecoverRequest defines model for RecoverRequest.
type RecoverRequest struct {
	Answers     []SecurityAnswerInput `json:"answers"`
	NewPassword string                `json:"new_password"`
	Username    string                `json:"username"`
}

// Region defines model for Region.
type Region struct {
	// Id Stable region key (india, europe, us)
	Id string `json:"id"`

	// Label Display name
	Label string `json:"label"`
}

// RegionUpdateRequest defines model for RegionUpdateRequest.
type RegionUpdateRequest struct {
	// Region One of the /regions catalogue ids
	Region string `json:"region"`
}

// RejectedPasteRow defines model for RejectedPasteRow.
type RejectedPasteRow struct {
	Date   string `json:"date"`
	Reason string `json:"reason"`
}

// SecurityAnswerInput defines model for SecurityAnswerInput.
type SecurityAnswerInput struct {
	// Answer Answer text; compared case-insensitively, surrounding whitespace ignored
	Answer string `json:"answer"`

	// QuestionId Question key from the catalogue
	QuestionId string `json:"question_id"`
}

// SecurityQuestion defines model for SecurityQuestion.
type SecurityQuestion struct {
	// Id Stable question key from the fixed catalogue
	Id     string `json:"id"`
	Prompt string `json:"prompt"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`

	// Region One of the /regions catalogue ids
	Region          string                `json:"region"`
	SecurityAnswers []SecurityAnswerInput `json:"security_answers"`

	// Username Allowed characters: A–Z a–z 0–9 _ -
	Username string `json:"username"`
}

// Summary defines model for Summary.
type Summary struct {
	// ChangePct Percent change vs previous close. Null when previous_close_value is zero.
	ChangePct *float64 `json:"change_pct,omitempty"`

	// ChangeValue total_current_value − previous_close_value (INR base).
	ChangeValue    *float64 `json:"change_value,omitempty"`
	ChangeValueEur *float64 `json:"change_value_eur,omitempty"`
	EurRate        *float64 `json:"eur_rate,omitempty"`

	// PerCurrency Per-currency change vs previous close, in native amounts (no FX conversion), so currency moves don't muddy the price move.
	PerCurrency *[]CurrencyChange `json:"per_currency,omitempty"`

	// PreviousCloseDate YYYY-MM-DD of the snapshot used as the previous close.
	PreviousCloseDate *string `json:"previous_close_date,omitempty"`

	// PreviousCloseValue Portfolio current value (INR base) at the most recent snapshot strictly before today — the previous close. Omitted when the user has no prior snapshot.
	PreviousCloseValue    *float64 `json:"previous_close_value,omitempty"`
	PreviousCloseValueEur *float64 `json:"previous_close_value_eur,omitempty"`
	TotalCost             *float64 `json:"total_cost,omitempty"`
	TotalCostEur          *float64 `json:"total_cost_eur,omitempty"`
	TotalCurrentValue     *float64 `json:"total_current_value,omitempty"`
	TotalCurrentValueEur  *float64 `json:"total_current_value_eur,omitempty"`
	TotalRealized         *float64 `json:"total_realized,omitempty"`
	TotalRealizedEur      *float64 `json:"total_realized_eur,omitempty"`
	TotalUnrealized       *float64 `json:"total_unrealized,omitempty"`
	TotalUnrealizedEur    *float64 `json:"total_unrealized_eur,omitempty"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	// Amount Total cash — debited (buy) or credited (sell, dividend); fees folded in
	Amount    *float64             `json:"amount,omitempty"`
	CreatedAt *time.Time           `json:"created_at,omitempty"`
	Currency  *TransactionCurrency `json:"currency,omitempty"`

	// Date Trade / ex date; orders the ledger
	Date *time.Time `json:"date,omitempty"`

	// HoldingId Owning holding's ObjectID
	HoldingId *string `json:"holding_id,omitempty"`

	// Id MongoDB ObjectID
	Id    *string `json:"id,omitempty"`
	Notes *string `json:"notes,omitempty"`

	// Quantity Shares (buy/sell/opening); unused for dividend
	Quantity *float64 `json:"quantity,omitempty"`

	// Ratio Split/bonus ratio, e.g. 2.0 = 2-for-1
	Ratio *float64 `json:"ratio,omitempty"`

	// RealizedSeed Opening only — carries a legacy realized P&L with no underlying sell
	RealizedSeed *float64         `json:"realized_seed,omitempty"`
	Type         *TransactionType `json:"type,omitempty"`
	UpdatedAt    *time.Time       `json:"updated_at,omitempty"`
}

// TransactionCurrency defines model for Transaction.Currency.
type TransactionCurrency string

// TransactionType defines model for Transaction.Type.
type TransactionType string

// TransactionInput defines model for TransactionInput.
type TransactionInput struct {
	Amount       *float64             `json:"amount,omitempty"`
	Date         time.Time            `json:"date"`
	Notes        *string              `json:"notes,omitempty"`
	Quantity     *float64             `json:"quantity,omitempty"`
	Ratio        *float64             `json:"ratio,omitempty"`
	RealizedSeed *float64             `json:"realized_seed,omitempty"`
	Type         TransactionInputType `json:"type"`
}

// TransactionInputType defines model for TransactionInput.Type.
type TransactionInputType string

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	CurrentPassword string  `json:"current_password"`
	Name            *string `json:"name,omitempty"`
	Username        *string `json:"username,omitempty"`
}

// UpdateSecurityQuestionsRequest defines model for UpdateSecurityQuestionsRequest.
type UpdateSecurityQuestionsRequest struct {
	CurrentPassword string                `json:"current_password"`
	SecurityAnswers []SecurityAnswerInput `json:"security_answers"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Disabled Hidden (reversibly blocked) by an admin
	Disabled bool `json:"disabled"`

	// GoldEnabled Physical-gold tracking enabled (super-admin toggled, PRD-003 §2.4)
	GoldEnabled bool `json:"gold_enabled"`

	// Id MongoDB ObjectID
	Id          string     `json:"id"`
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`

	// Locked Security-question recovery locked after three wrong attempts
	Locked bool `json:"locked"`

	// MustChangePassword Forced onboarding pending (bootstrap super admin)
	MustChangePassword bool   `json:"must_change_password"`
	Name               string `json:"name"`

	// Region Oversight region (india, europe, us); empty for the super admin
	Region string   `json:"region"`
	Role   UserRole `json:"role"`

	// SecurityQuestionIds The catalogue keys of the account's chosen questions (own account only)
	SecurityQuestionIds *[]string `json:"security_question_ids,omitempty"`

	// Username Username as originally typed (uniqueness is case-insensitive)
	Username string `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserID defines model for UserID.
type UserID = string

// BadGateway defines model for BadGateway.
type BadGateway = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// GoldUnavailable defines model for GoldUnavailable.
type GoldUnavailable = Error

// Locked defines model for Locked.
type Locked = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type GoldUnavailableJSONResponse Error

type LockedJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error
