---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--format, parsable]
        entry: yamllint -c .yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
  - repo: local
    hooks:
      - id: go-fmt
        name: gofmt
        entry: gofmt -l -w .
        language: system
        types: [go]
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'cd backend && golangci-lint run --timeout=1m ./...'
        language: system
        types: [go]
        pass_filenames: false
