/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all holdings */
        get: operations["listHoldings"];
        put?: never;
        /** Add a new holding */
        post: operations["createHolding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        /** Get a single holding */
        get: operations["getHolding"];
        /** Update a holding */
        put: operations["updateHolding"];
        post?: never;
        /** Delete a holding */
        delete: operations["deleteHolding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all holdings enriched with live market prices
         * @description Fetches current prices from Yahoo Finance for every holding that has a
         *     `symbol` set. Also returns the live INR→EUR exchange rate.
         *     Results are cached for 5 minutes to avoid rate-limiting.
         */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio-level summary with live P&L */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get live price for any symbol */
        get: operations["getMarketPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/forex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get forex exchange rate */
        get: operations["getForexRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Holding: {
            /** @description MongoDB ObjectID */
            id?: string;
            /** @description Display name (e.g. "TCS", "GOLD BEES") */
            script?: string;
            /** @description Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL") */
            symbol?: string;
            /** @enum {string} */
            exchange?: "NSE" | "BSE" | "NYSE" | "NASDAQ" | "OTHER";
            /** @enum {string} */
            type?: "stock" | "etf";
            /**
             * Format: double
             * @description Current quantity held
             */
            stocks_owned?: number;
            /**
             * Format: double
             * @description Average purchase price per share in the holding's currency
             */
            avg_cost_price?: number;
            /**
             * Format: double
             * @description Profit/loss from shares already sold, in the holding's currency
             */
            realized_pnl?: number;
            /**
             * @description Currency in which avg_cost_price and realized_pnl are denominated
             * @default INR
             * @enum {string}
             */
            currency: "INR" | "EUR";
            notes?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        HoldingInput: {
            script: string;
            symbol?: string;
            /** @enum {string} */
            exchange: "NSE" | "BSE" | "NYSE" | "NASDAQ" | "OTHER";
            /** @enum {string} */
            type: "stock" | "etf";
            /**
             * Format: double
             * @default 0
             */
            stocks_owned: number;
            /**
             * Format: double
             * @default 0
             */
            avg_cost_price: number;
            /**
             * Format: double
             * @default 0
             */
            realized_pnl: number;
            /**
             * @description Currency in which avg_cost_price and realized_pnl are denominated
             * @default INR
             * @enum {string}
             */
            currency: "INR" | "EUR";
            notes?: string;
        };
        HoldingWithPrice: components["schemas"]["Holding"] & {
            /** Format: double */
            current_price?: number;
            /**
             * Format: double
             * @description stocks_owned × avg_cost_price
             */
            cost_price?: number;
            /**
             * Format: double
             * @description stocks_owned × current_price
             */
            current_value?: number;
            /**
             * Format: double
             * @description current_value − cost_price
             */
            unrealized_pnl?: number;
            /** Format: double */
            cost_price_eur?: number;
            /** Format: double */
            current_value_eur?: number;
            /** Format: double */
            unrealized_pnl_eur?: number;
            /** Format: double */
            realized_pnl_eur?: number;
            price_error?: string;
        };
        PricesResponse: {
            holdings?: components["schemas"]["HoldingWithPrice"][];
            /**
             * Format: double
             * @description Live INR→EUR rate used for conversions
             */
            eur_rate?: number;
        };
        Summary: {
            /** Format: double */
            total_cost?: number;
            /** Format: double */
            total_current_value?: number;
            /** Format: double */
            total_unrealized?: number;
            /** Format: double */
            total_realized?: number;
            /** Format: double */
            total_cost_eur?: number;
            /** Format: double */
            total_current_value_eur?: number;
            /** Format: double */
            total_unrealized_eur?: number;
            /** Format: double */
            total_realized_eur?: number;
            /** Format: double */
            eur_rate?: number;
        };
        Error: {
            error?: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Upstream (Yahoo Finance) error */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listHoldings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of holdings sorted by script name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"][];
                };
            };
        };
    };
    createHolding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingInput"];
            };
        };
        responses: {
            /** @description Created holding */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holding found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingInput"];
            };
        };
        responses: {
            /** @description Updated holding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example deleted */
                        message?: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings with live prices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated portfolio metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
        };
    };
    getMarketPrice: {
        parameters: {
            query: {
                /**
                 * @description Yahoo Finance ticker (e.g. TCS.NS, AAPL, GOLDBEES.NS)
                 * @example TCS.NS
                 */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        symbol?: string;
                        /** Format: double */
                        price?: number;
                        currency?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    getForexRate: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exchange rate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from?: string;
                        to?: string;
                        /**
                         * Format: double
                         * @description 1 unit of `from` in `to`
                         */
                        rate?: number;
                    };
                };
            };
        };
    };
}
