/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all holdings */
        get: operations["listHoldings"];
        put?: never;
        /** Add a new holding */
        post: operations["createHolding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        /** Get a single holding */
        get: operations["getHolding"];
        /** Update a holding */
        put: operations["updateHolding"];
        post?: never;
        /** Delete a holding */
        delete: operations["deleteHolding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all holdings enriched with live market prices
         * @description Fetches current prices from Yahoo Finance for every holding that has a
         *     `symbol` set. Also returns the live INR→EUR exchange rate.
         *     Results are cached for 5 minutes to avoid rate-limiting.
         */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio-level summary with live P&L */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get live price for any symbol */
        get: operations["getMarketPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/forex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get forex exchange rate */
        get: operations["getForexRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Region catalogue
         * @description Fixed list of oversight regions for the signup dropdown.
         */
        get: operations["getRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/security-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security-question catalogue */
        get: operations["getSecurityQuestionCatalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and log in */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recover/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch the security questions for an account (forgot password, step 1)
         * @description Username travels in the body (not the URL) so it stays out of access logs.
         */
        post: operations["getRecoveryQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a forgotten password by answering all three security questions
         * @description Three wrong attempts lock recovery (HTTP 423) until someone authorised
         *     resets it: an admin for a user, the super admin for an admin.
         */
        post: operations["recoverPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change own password
         * @description Signs out all other sessions.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change own name and/or username */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/security-questions/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace own security questions and answers */
        put: operations["updateSecurityQuestions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete forced first-login onboarding
         * @description Atomically sets a real password and three real security questions and
         *     clears `must_change_password`. Used by the bootstrap super admin.
         */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users the caller oversees
         * @description Admins see the `user` accounts of their own region; the super admin
         *     sees every account. Hidden users are excluded unless `include_hidden`.
         */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List admins and the super admin (super admin only) */
        get: operations["adminListAdmins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        /** Get one user in scope */
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        /** Permanently delete a user and their holdings */
        delete: operations["adminDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/reset-lockout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock a user who failed security-question recovery */
        post: operations["adminResetLockout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide a user (reversibly block access, keep data) */
        post: operations["adminHideUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate a hidden user */
        post: operations["adminReactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote a user to admin of their region (super admin only) */
        post: operations["adminPromoteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/demote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demote an admin back to a normal user (super admin only) */
        post: operations["adminDemoteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/region": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Move an account to a different region (super admin only) */
        put: operations["adminSetUserRegion"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        /** List a user's holdings (act on their behalf) */
        get: operations["adminListUserHoldings"];
        put?: never;
        /** Add a holding to a user's portfolio */
        post: operations["adminCreateUserHolding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/holdings/{holdingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
                /** @description MongoDB ObjectID of the holding */
                holdingId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a holding in a user's portfolio */
        put: operations["adminUpdateUserHolding"];
        post?: never;
        /** Delete a holding from a user's portfolio */
        delete: operations["adminDeleteUserHolding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A user's holdings enriched with live prices */
        get: operations["adminGetUserPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A user's portfolio summary */
        get: operations["adminGetUserSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Holding: {
            /** @description MongoDB ObjectID */
            id?: string;
            /** @description Display name (e.g. "TCS", "GOLD BEES") */
            script?: string;
            /** @description Yahoo Finance ticker (e.g. "TCS.NS", "GOLDBEES.NS", "AAPL") */
            symbol?: string;
            /** @enum {string} */
            exchange?: "NSE" | "BSE" | "NYSE" | "NASDAQ" | "OTHER";
            /** @enum {string} */
            type?: "stock" | "etf";
            /**
             * Format: double
             * @description Current quantity held
             */
            stocks_owned?: number;
            /**
             * Format: double
             * @description Average purchase price per share in the holding's currency
             */
            avg_cost_price?: number;
            /**
             * Format: double
             * @description Profit/loss from shares already sold, in the holding's currency
             */
            realized_pnl?: number;
            /**
             * @description Currency in which avg_cost_price and realized_pnl are denominated
             * @default INR
             * @enum {string}
             */
            currency: "INR" | "EUR";
            notes?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        HoldingInput: {
            script: string;
            symbol?: string;
            /** @enum {string} */
            exchange: "NSE" | "BSE" | "NYSE" | "NASDAQ" | "OTHER";
            /** @enum {string} */
            type: "stock" | "etf";
            /**
             * Format: double
             * @default 0
             */
            stocks_owned: number;
            /**
             * Format: double
             * @default 0
             */
            avg_cost_price: number;
            /**
             * Format: double
             * @default 0
             */
            realized_pnl: number;
            /**
             * @description Currency in which avg_cost_price and realized_pnl are denominated
             * @default INR
             * @enum {string}
             */
            currency: "INR" | "EUR";
            notes?: string;
        };
        Error: {
            error?: string;
        };
        HoldingWithPrice: components["schemas"]["Holding"] & {
            /** Format: double */
            current_price?: number;
            /**
             * Format: double
             * @description stocks_owned × avg_cost_price
             */
            cost_price?: number;
            /**
             * Format: double
             * @description stocks_owned × current_price
             */
            current_value?: number;
            /**
             * Format: double
             * @description current_value − cost_price
             */
            unrealized_pnl?: number;
            /** Format: double */
            cost_price_eur?: number;
            /** Format: double */
            current_value_eur?: number;
            /** Format: double */
            unrealized_pnl_eur?: number;
            /** Format: double */
            realized_pnl_eur?: number;
            price_error?: string;
        };
        PricesResponse: {
            holdings?: components["schemas"]["HoldingWithPrice"][];
            /**
             * Format: double
             * @description Live INR→EUR rate used for conversions
             */
            eur_rate?: number;
        };
        Summary: {
            /** Format: double */
            total_cost?: number;
            /** Format: double */
            total_current_value?: number;
            /** Format: double */
            total_unrealized?: number;
            /** Format: double */
            total_realized?: number;
            /** Format: double */
            total_cost_eur?: number;
            /** Format: double */
            total_current_value_eur?: number;
            /** Format: double */
            total_unrealized_eur?: number;
            /** Format: double */
            total_realized_eur?: number;
            /** Format: double */
            eur_rate?: number;
        };
        Region: {
            /** @description Stable region key (india, europe, us) */
            id: string;
            /** @description Display name */
            label: string;
        };
        SecurityQuestion: {
            /** @description Stable question key from the fixed catalogue */
            id: string;
            prompt: string;
        };
        SecurityAnswerInput: {
            /** @description Question key from the catalogue */
            question_id: string;
            /** @description Answer text; compared case-insensitively, surrounding whitespace ignored */
            answer: string;
        };
        SignupRequest: {
            /** @description Allowed characters: A–Z a–z 0–9 _ - */
            username: string;
            name: string;
            password: string;
            /** @description One of the /regions catalogue ids */
            region: string;
            security_answers: components["schemas"]["SecurityAnswerInput"][];
        };
        User: {
            /** @description MongoDB ObjectID */
            id: string;
            /** @description Username as originally typed (uniqueness is case-insensitive) */
            username: string;
            name: string;
            /** @enum {string} */
            role: "user" | "admin" | "superadmin";
            /** @description Oversight region (india, europe, us); empty for the super admin */
            region: string;
            /** @description Hidden (reversibly blocked) by an admin */
            disabled: boolean;
            /** @description Security-question recovery locked after three wrong attempts */
            locked: boolean;
            /** @description Forced onboarding pending (bootstrap super admin) */
            must_change_password: boolean;
            /** @description The catalogue keys of the account's chosen questions (own account only) */
            security_question_ids?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_login_at?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RecoverQuestionsRequest: {
            username: string;
        };
        RecoverRequest: {
            username: string;
            answers: components["schemas"]["SecurityAnswerInput"][];
            new_password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        UpdateProfileRequest: {
            current_password: string;
            name?: string;
            username?: string;
        };
        UpdateSecurityQuestionsRequest: {
            current_password: string;
            security_answers: components["schemas"]["SecurityAnswerInput"][];
        };
        OnboardingRequest: {
            current_password: string;
            new_password: string;
            security_answers: components["schemas"]["SecurityAnswerInput"][];
        };
        RegionUpdateRequest: {
            /** @description One of the /regions catalogue ids */
            region: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Upstream (Yahoo Finance) error */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Username already taken */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not logged in, or credentials/answers rejected */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Logged in but not allowed (role, scope, or hidden account) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Recovery locked after three wrong security-answer attempts */
        Locked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description MongoDB ObjectID of the target user */
        UserID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listHoldings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of holdings sorted by script name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"][];
                };
            };
        };
    };
    createHolding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingInput"];
            };
        };
        responses: {
            /** @description Created holding */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holding found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingInput"];
            };
        };
        responses: {
            /** @description Updated holding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example deleted */
                        message?: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings with live prices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated portfolio metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
        };
    };
    getMarketPrice: {
        parameters: {
            query: {
                /**
                 * @description Yahoo Finance ticker (e.g. TCS.NS, AAPL, GOLDBEES.NS)
                 * @example TCS.NS
                 */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        symbol?: string;
                        /** Format: double */
                        price?: number;
                        currency?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    getForexRate: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exchange rate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        from?: string;
                        to?: string;
                        /**
                         * Format: double
                         * @description 1 unit of `from` in `to`
                         */
                        rate?: number;
                    };
                };
            };
        };
    };
    getRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
        };
    };
    getSecurityQuestionCatalogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityQuestion"][];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created; session cookie issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; session cookie issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            423: components["responses"]["Locked"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated; cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The logged-in account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRecoveryQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoverQuestionsRequest"];
            };
        };
        responses: {
            /** @description The three questions the account chose at signup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityQuestion"][];
                };
            };
            404: components["responses"]["NotFound"];
            423: components["responses"]["Locked"];
        };
    };
    recoverPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoverRequest"];
            };
        };
        responses: {
            /** @description Password reset; all sessions invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            423: components["responses"]["Locked"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; other sessions invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSecurityQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSecurityQuestionsRequest"];
            };
        };
        responses: {
            /** @description Security questions replaced */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Onboarding complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users in scope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminListAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts with role admin or superadmin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User and holdings deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminResetLockout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lockout cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminHideUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User hidden */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminReactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User reactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminPromoteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminDemoteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminSetUserRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListUserHoldings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's holdings sorted by script name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminCreateUserHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingInput"];
            };
        };
        responses: {
            /** @description Created holding */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    adminUpdateUserHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
                /** @description MongoDB ObjectID of the holding */
                holdingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingInput"];
            };
        };
        responses: {
            /** @description Updated holding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminDeleteUserHolding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
                /** @description MongoDB ObjectID of the holding */
                holdingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example deleted */
                        message?: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminGetUserPrices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holdings with live prices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminGetUserSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MongoDB ObjectID of the target user */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated portfolio metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
